AWSTemplateFormatVersion: '2010-09-09'

Description: S3 to S3 file copy using lambda 

Parameters:

  SourceBucketName:
    Type: String
    Description: Name of source S3 bucket

  DestinationBucketName:
    Type: String
    Description: Name of the destination S3 bucket

  LambdaCodeBucket:                                      
    Type: String
    Description: S3 bucket containing Lambda ZIP file

  LambdaCodeKey:
    Type: String
    Description: S3 path of Lambda ZIP file


Resources:

  SourceBucket:
    Type: AWS::S3::Bucket

    DependsOn:
      - S3InvokePermission

    Properties:
      BucketName: !Ref SourceBucketName

      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LambdaFunction.Arn


  DestinationBucket:
    Type: AWS::S3::Bucket

    Properties:
      BucketName: !Ref DestinationBucketName


  LambdaExecutionRole:
    Type: AWS::IAM::Role

    Properties:

      AssumeRolePolicyDocument:                  
        Version: '2012-10-17'                    

        Statement:
          - Effect: Allow

            Principal:                          
              Service:
                - lambda.amazonaws.com

            Action:
              - sts:AssumeRole                  


      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole           


      Policies:                                 

        - PolicyName: S3AccessPolicy

          PolicyDocument:
            Version: '2012-10-17'

            Statement:

              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${SourceBucketName}/*'


              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${DestinationBucketName}/*'        


  LambdaFunction:
    Type: AWS::Lambda::Function

    Properties:

      Runtime: python3.12

      Handler: lambda_function.lambda_handler     

      Role: !GetAtt LambdaExecutionRole.Arn

      Timeout: 60                                 
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey


  S3InvokePermission:
    Type: AWS::Lambda::Permission

    Properties:

      Action: lambda:InvokeFunction

      FunctionName: !Ref LambdaFunction

      Principal: s3.amazonaws.com           

      SourceAccount: !Ref AWS::AccountId

      SourceArn: !Sub 'arn:${AWS::Partition}:s3:::${SourceBucketName}'
      

Outputs:

  SourceBucket:
    Description: Source S3 bucket name
    Value: !Ref SourceBucket

  DestinationBucket:
    Description: Destination S3 bucket name
    Value: !Ref DestinationBucket

  LambdaFunction:
    Description: Lambda function name
    Value: !Ref LambdaFunction